package com.example.logindemo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.bean.ShoppingBean;
import com.example.bean.User;
import com.example.bean.UserInfo;

import com.example.logindemo.greendao.ShoppingBeanDao;
import com.example.logindemo.greendao.UserDao;
import com.example.logindemo.greendao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shoppingBeanDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final ShoppingBeanDao shoppingBeanDao;
    private final UserDao userDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shoppingBeanDaoConfig = daoConfigMap.get(ShoppingBeanDao.class).clone();
        shoppingBeanDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        shoppingBeanDao = new ShoppingBeanDao(shoppingBeanDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(ShoppingBean.class, shoppingBeanDao);
        registerDao(User.class, userDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        shoppingBeanDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public ShoppingBeanDao getShoppingBeanDao() {
        return shoppingBeanDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
